development:
  bucket: deliverypaws
  access_key_id: AKIAJCOUZLD62QTX3ICQ
  secret_access_key: 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
  

test:
  bucket: deliverypaws
  access_key_id: AKIAJCOUZLD62QTX3ICQ
  secret_access_key: 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
  

production:
  bucket: deliverypaws
  access_key_id: AKIAJCOUZLD62QTX3ICQ
  secret_access_key: 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
  
